# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MY_AsQe6BqMiEVWR1iBuYTl9drFVanSo
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import pchip_interpolate

# Configuración de la interfaz
st.set_page_config(layout="wide", page_title="Diagrama de Equilibrio Líquido-Vapor")

st.title("📊 Herramienta de Análisis de Diagramas de Fase en Equilibrio")
st.write("Esta aplicación interactiva permite ajustar curvas de equilibrio, calcular la regla de la palanca y analizar composiciones.")

# Inicializar estados de la sesión para líneas manuales
if 'manual_lines' not in st.session_state:
    st.session_state.manual_lines = []

# ==========================================
# 1. ENTRADA DE DATOS (PREGUNTA AL USUARIO)
# ==========================================
st.sidebar.header("📋 1. Configuración de Datos")

# Pregunta si el eje Y es Temperatura o Presión
eje_y_tipo = st.sidebar.radio("Selecciona la variable del eje Y:", ["Temperatura", "Presión"])
unidad = "K" if eje_y_tipo == "Temperatura" else "atm/bar"

st.sidebar.subheader("Puntos de Datos de Equilibrio")
st.sidebar.write("Introduce tus datos experimentales puntuales (separados por comas):")

# Valores por defecto realistas (sistema Benceno-Tolueno) modificables por el usuario
default_x = "0.0, 0.1, 0.2, 0.3, 0.5, 0.7, 0.9, 1.0"
default_y = "0.0, 0.22, 0.41, 0.57, 0.78, 0.90, 0.98, 1.0"
default_tp = "373.15, 365.0, 358.5, 353.0, 345.0, 340.0, 338.5, 337.65" if eje_y_tipo == "Temperatura" else "1.0, 1.2, 1.5, 1.8, 2.3, 2.8, 3.2, 3.5"

x_input = st.sidebar.text_input("Fracción molar Líquido (x):", default_x)
y_input = st.sidebar.text_input("Fracción molar Vapor (y):", default_y)
tp_input = st.sidebar.text_input(f"{eje_y_tipo} ({unidad}):", default_tp)

# Procesamiento y conversión de datos de texto a arreglos numéricos
try:
    x_arr = np.array([float(i.strip()) for i in x_input.split(",") if i.strip()])
    y_arr = np.array([float(i.strip()) for i in y_input.split(",") if i.strip()])
    tp_arr = np.array([float(i.strip()) for i in tp_input.split(",") if i.strip()])

    if not (len(x_arr) == len(y_arr) == len(tp_arr)):
        st.sidebar.error("⚠️ Error: Los vectores de x, y y T/P deben tener el mismo tamaño.")
        st.stop()
except ValueError:
    st.sidebar.error("⚠️ Error: Ingresa únicamente números separados por comas.")
    st.stop()

# Mostrar la tabla de datos procesados
df_datos = pd.DataFrame({'x (Líquido)': x_arr, 'y (Vapor)': y_arr, eje_y_tipo: tp_arr})
st.sidebar.dataframe(df_datos, use_container_width=True)

# ==========================================
# AJUSTE DE LA MEJOR CURVA POSIBLE (PCHIP Spline)
# ==========================================
# Usamos PCHIP porque ajusta una curva suave perfecta sin las oscilaciones erráticas de las funciones polinómicas tradicionales
sort_idx = np.argsort(tp_arr)
x_sorted, y_sorted, tp_sorted = x_arr[sort_idx], y_arr[sort_idx], tp_arr[sort_idx]

tp_smooth = np.linspace(tp_sorted.min(), tp_sorted.max(), 300)
x_smooth = pchip_interpolate(tp_sorted, x_sorted, tp_smooth)
y_smooth = pchip_interpolate(tp_sorted, y_sorted, tp_smooth)

# ==========================================
# 2. ALIMENTACIÓN Y REGLA DE LA PALANCA MÓVIL
# ==========================================
st.sidebar.header("⛽ 2. Parámetros de Alimentación")
z_feed = st.sidebar.slider("Composición global de alimentación (z):", 0.0, 1.0, 0.275, 0.005)

st.sidebar.subheader("🕹️ Avanzar/Retroceder en la Regla")
min_tp, max_tp = float(tp_sorted.min()), float(tp_sorted.max())
# Control deslizable que actúa como tu botón para subir y bajar manteniendo como eje central la línea 'z'
current_tp = st.sidebar.slider(f"Mover regla vertical en {eje_y_tipo}:", min_tp, max_tp, (min_tp + max_tp)/2, 0.1)

# Calcular las intersecciones exactas de la regla a la altura seleccionada
x_c = np.clip(pchip_interpolate(tp_sorted, x_sorted, current_tp), 0.0, 1.0)
y_c = np.clip(pchip_interpolate(tp_sorted, y_sorted, current_tp), 0.0, 1.0)

# Organizar extremos geométricos (Izquierda y Derecha)
if x_c > y_c:
    left_curve, right_curve = y_c, x_c
else:
    left_curve, right_curve = x_c, y_c

# Mostrar métricas numéricas
st.header("🧮 Cálculos en Tiempo Real")
col1, col2, col3, col4 = st.columns(4)

if left_curve <= z_feed <= right_curve:
    L_dist = abs(z_feed - left_curve)
    V_dist = abs(right_curve - z_feed)
    frac_vapor = V_dist / (V_dist + L_dist) if (V_dist + L_dist) > 0 else 0.0

    col1.metric(f"{eje_y_tipo} Seleccionada", f"{current_tp:.2f} {unidad}")
    col2.metric("Distancia L (Segmento Izq.)", f"{L_dist:.4f}")
    col3.metric("Distancia V (Segmento Der.)", f"{V_dist:.4f}")
    col4.metric("Fracción de Vapor V/(V+L)", f"{frac_vapor:.4f}")
else:
    col1.metric(f"{eje_y_tipo} Seleccionada", f"{current_tp:.2f} {unidad}")
    col2.write("Fuera de la región Bifásica")
    col3.write("")
    col4.metric("Fracción de Vapor", "0.0 o 1.0")

# ==========================================
# 3. GRAFICACIÓN DINÁMICA
# ==========================================
fig, ax = plt.subplots(figsize=(10, 6))

# Graficar las curvas ajustadas suaves
ax.plot(x_smooth, tp_smooth, color='red', label='Línea de Líquido Saturado', linewidth=2)
ax.plot(y_smooth, tp_smooth, color='blue', linestyle='--', label='Línea de Vapor Saturado', linewidth=2)

# Graficar los puntos originales provistos por el usuario
ax.scatter(x_arr, tp_arr, color='darkred', marker='x', s=60, label='Puntos datos Líquido')
ax.scatter(y_arr, tp_arr, color='darkblue', marker='o', s=50, label='Puntos datos Vapor')

# Línea vertical fija de Alimentación
ax.axvline(x=z_feed, color='#0f2c59', linewidth=2.5, label=f'Alimentación (z = {z_feed})')

# Si estamos en zona bifásica, dibujar la regla horizontal (Tie-line) con marcas 'L' y 'V'
if left_curve <= z_feed <= right_curve:
    ax.plot([left_curve, right_curve], [current_tp, current_tp], color='black', linewidth=2.5, marker='|', markersize=12)
    ax.text((left_curve + z_feed)/2, current_tp + (max_tp-min_tp)*0.015, 'L', fontsize=12, weight='bold', ha='center')
    ax.text((z_feed + right_curve)/2, current_tp + (max_tp-min_tp)*0.015, 'V', fontsize=12, weight='bold', ha='center')

# Marcador central de la regla móvil
ax.scatter([z_feed], [current_tp], color='black', marker='+', s=150, zorder=5)

# ==========================================
# CONTROLES EXTRA: LÍNEAS MANUALES Y PUNTERO
# ==========================================
st.sidebar.header("🛠️ 3. Añadir Líneas Manuales")
tipo_linea = st.sidebar.selectbox("Tipo:", ["Horizontal", "Vertical"])
valor_linea = st.sidebar.number_input("Valor de la coordenada:", min_value=0.0, max_value=500.0, value=0.5, step=0.05)

if st.sidebar.button("➕ Añadir Línea"):
    st.session_state.manual_lines.append({'tipo': tipo_linea, 'valor': valor_linea})
if st.sidebar.button("🗑️ Borrar Líneas"):
    st.session_state.manual_lines = []

# Trazar líneas creadas por el usuario
for line in st.session_state.manual_lines:
    if line['tipo'] == "Horizontal":
        ax.axhline(y=line['valor'], color='gray', linestyle=':', alpha=0.7)
    else:
        ax.axvline(x=line['valor'], color='gray', linestyle=':', alpha=0.7)

# PUNTERO INTERACTIVO AUTOMÁTICO
st.sidebar.header("🎯 4. Puntero Equivalente")
pos_puntero = st.sidebar.slider("Mover Puntero sobre Curvas:", min_tp, max_tp, current_tp)
x_p = pchip_interpolate(tp_sorted, x_sorted, pos_puntero)
y_p = pchip_interpolate(tp_sorted, y_sorted, pos_puntero)

# Traza la proyección horizontal automática que une la curva azul y la roja
ax.plot([x_p, y_p], [pos_puntero, pos_puntero], color='green', linestyle=':', alpha=0.8)
ax.scatter([x_p, y_p], [pos_puntero, pos_puntero], color='green', marker='s', s=40)

st.sidebar.info(f"📍 **Equivalencias del Puntero:**\n- Líquido Equivalente (x): {x_p:.4f}\n- Vapor Equivalente (y): {y_p:.4f}")

# Ajustes visuales de la cuadrícula idénticos a tu imagen
ax.set_xlabel("Fracción Molar (x, y)", fontsize=11)
ax.set_ylabel(f"{eje_y_tipo} ({unidad})", fontsize=11)
ax.set_xlim(0, 1)
ax.set_xticks(np.arange(0, 1.05, 0.05))
ax.grid(True, which='both', linestyle='-', linewidth=0.5, color='lightgray')
ax.legend(loc='best')
plt.tight_layout()

st.pyplot(fig)